### ISSUE TITLE
Stingray required ?

### ISSUE THREAD

**Issue by Krammig** [pmachapman/eudora-win#2]
Thanks for this. However it seems it cannot be compiled sue to the requirement of Stingray at least which appears to be a big investment. 

Did you use Stingray at your end ?
Do you have any alternative suggestions on how to approach this ?

Thanks

**Comment by pmachapman** [comment]
Yes, I used Stingray Objective Toolkit 12 to compile it, however, even with that there is still one or two classes missing that need to be recreated (that has been on my todo list for a while).

There is currently no alternative available, unfortunately, beyond rewriting the project to use something like MFC.

**Comment by Krammig** [comment]
Thanks for the reply. 

Is Stingray Objective Toolkit 12 readily available somewhere even as a demo or is it a Purchase only option. Seems very expensive for what it is. 

Thanks

**Comment by pmachapman** [comment]
Not that I am aware of. 12 is an old version - I used to use it at a previous job, but yes, it is expensive.

**Comment by Krammig** [comment]
Ok thanks
